# GoReleaser config for fetch-ssh-keys (Python/uv project)
# This config builds a tarball, attaches it to GitHub releases, and publishes Homebrew and other archives.
version: 2

project_name: fetch-ssh-keys

metadata:

builds:
  - builder: uv
    buildmode: wheel
    tool: uv

nfpms:
  - maintainer: "Mathieu Bressolle Chataigner <mathieu@example.com>"
    license: "MIT"
    description: "A tool to fetch SSH public keys from various sources."
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    dependencies:
      - python3
    bindir: /usr/local/bin
