# GoReleaser configuration for fetch_ssh_keys Go build
# Make sure to check the documentation at https://goreleaser.com

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # Ensure Go modules are tidy
    - go mod tidy -C ./go

builds:
  # Go build
  - id: fetch_ssh_keys_go
    main: ./go
    binary: fetch_ssh_keys
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
  
  # Rust build
  - id: my_ssh_keys_rust
    builder: rust
    binary: my-ssh-keys
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

nfpms:
  - id: default
    package_name: fetch-ssh-keys
    maintainer: "Mathieu Bressolle Chataigner <mathieui@example.com>"
    description: "Fetch SSH public keys from common providers"
    homepage: "https://github.com/mchataigner/my_ssh_keys"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/fetch-ssh-keys/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/fetch-ssh-keys/README.md

brews:
  - name: fetch-ssh-keys
    homepage: "https://github.com/mchataigner/my_ssh_keys"
    description: "Fetch SSH public keys from common providers"
    license: MIT
    repository:
      owner: mchataigner
      name: homebrew-tap
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    install: |
      bin.install "fetch_ssh_keys"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
